Repository drakiez92/IT008-VisualProgramming, pull requests merged in 2021-12, with the labels that each got.

#78 hotfix
  ViewModels/OrderPageViewModel.cs
  ViewModels/ProductPageViewModel.cs
Labels: wontfix

#79 Feature/purchase page
  Resources/ViewModelsRes.xaml
  ViewModels/CartPageViewModel.cs
  ViewModels/PurchasePageViewModel.cs
  Views/DashBoardPages/CartPage.xaml
  Views/DashBoardPages/PurchasePage.xaml
  Views/DashBoardPages/PurchasePage.xaml.cs
  Views/SharedPages/CheckoutPage.xaml
  Views/SharedPages/CheckoutPage.xaml.cs
Labels: enhancement

#88 Feature/myshoppage
  Converters/BooleanConverter.cs
  Resources/ConvertersRes.xaml
  SharedControl/EditProductDialog.xaml
  SharedControl/ProductCardManaged.xaml
  SharedControl/ProductCardManaged.xaml.cs
  ViewModels/MyShopViewModel.cs
  Views/DashBoardPages/MyShopPage.xaml
  Views/DashBoardPages/MyShopPage.xaml.cs
  Views/DashBoardPages/MyShopPages/AboutTab.xaml
  Views/DashBoardPages/MyShopPages/AboutTab.xaml.cs
  Views/DashBoardPages/MyShopPages/AllProductTab.xaml
  Views/DashBoardPages/MyShopPages/AllProductTab.xaml.cs
  Views/DashBoardPages/MyShopPages/HomeTab.xaml
  Views/DashBoardPages/MyShopPages/HomeTab.xaml.cs
  Views/DashBoardPages/MyShopPages/ProductManagerTab.xaml
  Views/DashBoardPages/MyShopPages/ProductManagerTab.xaml.cs
Labels: enhancement

#91 edit avatar and cover
  ViewModels/MyShopViewModel.cs
  Views/DashBoardPages/MyShopPage.xaml
  Views/SharedPages/ProductPage.xaml
Labels: documentation
